#!/bin/bash

# Use the /proc filesystem to find processes with "bash" in their name
for pid in /proc/*/; do
  pid=${pid%*/}
  name=$(tr '\0' ' ' < "$pid/cmdline")
  if [[ $name == *"bash"* ]]; then
    echo "${pid##*/} $name"
  fi
done
